// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/faker.proto

package faker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Faker service

func NewFakerEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Faker service

type FakerService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Faker_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Faker_PingPongService, error)
	FakeAddress(ctx context.Context, in *FakeSeed, opts ...client.CallOption) (*FakeAddressResponse, error)
}

type fakerService struct {
	c    client.Client
	name string
}

func NewFakerService(name string, c client.Client) FakerService {
	return &fakerService{
		c:    c,
		name: name,
	}
}

func (c *fakerService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Faker.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fakerService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Faker_StreamService, error) {
	req := c.c.NewRequest(c.name, "Faker.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &fakerServiceStream{stream}, nil
}

type Faker_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type fakerServiceStream struct {
	stream client.Stream
}

func (x *fakerServiceStream) Close() error {
	return x.stream.Close()
}

func (x *fakerServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *fakerServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *fakerServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *fakerServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fakerService) PingPong(ctx context.Context, opts ...client.CallOption) (Faker_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Faker.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &fakerServicePingPong{stream}, nil
}

type Faker_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type fakerServicePingPong struct {
	stream client.Stream
}

func (x *fakerServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *fakerServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *fakerServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *fakerServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *fakerServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *fakerServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fakerService) FakeAddress(ctx context.Context, in *FakeSeed, opts ...client.CallOption) (*FakeAddressResponse, error) {
	req := c.c.NewRequest(c.name, "Faker.FakeAddress", in)
	out := new(FakeAddressResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Faker service

type FakerHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Faker_StreamStream) error
	PingPong(context.Context, Faker_PingPongStream) error
	FakeAddress(context.Context, *FakeSeed, *FakeAddressResponse) error
}

func RegisterFakerHandler(s server.Server, hdlr FakerHandler, opts ...server.HandlerOption) error {
	type faker interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
		FakeAddress(ctx context.Context, in *FakeSeed, out *FakeAddressResponse) error
	}
	type Faker struct {
		faker
	}
	h := &fakerHandler{hdlr}
	return s.Handle(s.NewHandler(&Faker{h}, opts...))
}

type fakerHandler struct {
	FakerHandler
}

func (h *fakerHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.FakerHandler.Call(ctx, in, out)
}

func (h *fakerHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.FakerHandler.Stream(ctx, m, &fakerStreamStream{stream})
}

type Faker_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type fakerStreamStream struct {
	stream server.Stream
}

func (x *fakerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *fakerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *fakerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *fakerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *fakerStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *fakerHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.FakerHandler.PingPong(ctx, &fakerPingPongStream{stream})
}

type Faker_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type fakerPingPongStream struct {
	stream server.Stream
}

func (x *fakerPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *fakerPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *fakerPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *fakerPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *fakerPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *fakerPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *fakerHandler) FakeAddress(ctx context.Context, in *FakeSeed, out *FakeAddressResponse) error {
	return h.FakerHandler.FakeAddress(ctx, in, out)
}
